### ISSUE TITLE
双音频识别

### ISSUE THREAD

**Issue by sternelee** [goldvideo/demuxer#1]
您好，我在用 demuxer的TSDemux来解封装时，该mpeg-ts是个双音频文件，导致播放时会出现双声音并导致播放问题(而且解析出来的数据stream_id都是一样的），有什么方式来识别音频1音频2，并只保留单条音频吗？

**Comment by gemxx** [comment]
> 您好，我在用 demuxer的TSDemux来解封装时，该mpeg-ts是个双音频文件，导致播放时会出现双声音并导致播放问题(而且解析出来的数据stream_id都是一样的），有什么方式来识别音频1音频2，并只保留单条音频吗？

您可以贴一个这样的ts文件吗？

**Comment by sternelee** [comment]
不好意思，原来是可以从demuxer后数据的pid来区分不同的音频，感谢您的demuxer
