### ISSUE TITLE
PID Filter in PesStream is Incorrect?

### ISSUE THREAD

**Issue by neodescis** [goldvideo/demuxer#2]
In the PesStream class, there is a filter on the PID, only allowing output for values of greater than 255. It's line 40 of pes.ts:

`if (packet.PID > 0x00ff && packet.PID < 0x1fff) {`

Why is this lower limit there? According to [the spec](https://en.wikipedia.org/wiki/MPEG_transport_stream#Packet_identifier_(PID)), the lower limit should be greater than 31, or 0x001f.

I have a hardware encoder that is outputting a PID of 68 on its video stream, and I can only demux it if I change this limit. Can this be changed?

**Comment by gemxx** [comment]
> In the PesStream class, there is a filter on the PID, only allowing output for values of greater than 255. It's line 40 of pes.ts:
> 
> `if (packet.PID > 0x00ff && packet.PID < 0x1fff) {`
> 
> Why is this lower limit there? According to [the spec](https://en.wikipedia.org/wiki/MPEG_transport_stream#Packet_identifier_(PID)), the lower limit should be greater than 31, or 0x001f.
> 
> I have a hardware encoder that is outputting a PID of 68 on its video stream, and I can only demux it if I change this limit. Can this be changed?

Originally I just want to avoid some[ table_ids defined by dvb](https://en.wikipedia.org/wiki/Program-specific_information#PSI_labels) , maybe this strategy is too strict.  The lower limit down to 0x001f is acceptable, it fixed in v2.1.3, just try it. Thanks for the issue report!

**Comment by neodescis** [comment]
Thanks very much for the quick fix, and all the work on this library. The new version works great for my video stream!
