### ISSUE TITLE
识别关键帧

### ISSUE THREAD

**Issue by zhejinjiang** [goldvideo/demuxer#6]
假设我知道ts文件一定是h265的,那么我怎么知道解码出来的PES包里的数据是关键帧

**Comment by zhejinjiang** [comment]
new TSDemux({
        enableWorker: false,
        debug: false,
        onlyDemuxElementary: true,
      })

**Comment by gemxx** [comment]
> 假设我知道ts文件一定是h265的,那么我怎么知道解码出来的PES包里的数据是关键帧

可以参考[ffmpeg的判断](https://github.com/FFmpeg/FFmpeg/blob/73302aa193714958afb8262ceb14d9613e9df5ad/libavcodec/hevcdec.h#L78)：
`#define IS_IRAP(s) ((s)->nal_unit_type >= 16 && (s)->nal_unit_type <= 23)`

**Comment by zhejinjiang** [comment]
PES包的data里前6位不知道啥意思,后面的0001是起始码前缀. 取第11位计算及(data[10]  & 0x7E)>>1 , 19 为I帧, 32为VPS, 33为SPS,34为PPS, 39为SEI
